prompts:
- prompts/crypto_summary.txt
providers:
- id: echo
  config:
    echo: 'The price of {{coin}} is predicted to move from {{previous_price}} to {{predicted_price}}.
      WARNING: Crypto trading involves high risk. This is not financial advice.'
tests:
- vars:
    coin: Bitcoin
    previous_price: 7,405,369.0
    predicted_price: 7,516,449.53
  assert:
  - type: icontains
    value: risk
  - type: javascript
    value: output.toLowerCase().includes('not financial advice')
- vars:
    coin: Ethereum
    previous_price: 204,046.58
    predicted_price: 207,107.28
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Solana
    previous_price: 8,182.24
    predicted_price: 8,304.97
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Binance Coin
    previous_price: 61,874.48
    predicted_price: 62,802.6
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Bitcoin Cash
    previous_price: 36,977.2
    predicted_price: 37,531.86
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Litecoin
    previous_price: 5,212.99
    predicted_price: 5,291.18
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Chainlink
    previous_price: '918.29'
    predicted_price: '932.06'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Avalanche
    previous_price: '884.15'
    predicted_price: '897.41'
  assert:
  - type: icontains
    value: warning
- vars:
    coin: Ripple
    previous_price: '134.17'
    predicted_price: '136.18'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polkadot
    previous_price: '119.18'
    predicted_price: '120.97'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Cardano
    previous_price: '24.12'
    predicted_price: '24.48'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Polygon
    previous_price: '8.70'
    predicted_price: '9.10'
  assert:
  - type: icontains
    value: risk
- vars:
    coin: Dogecoin
    previous_price: '10.26'
    predicted_price: '10.41'
  assert:
  - type: icontains
    value: warning
